title: Owen Gibbons | Network Engineer
description: Network engineering portfolio
author: Owen Gibbons
email: owen.gibbons [at] proton.me
url: "https://owengibbons.com"
linkedin_username: owen-j-gibbons
github_username: owen-gibbons
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - plan.md
  - contact.md
minima:
  skin: auto
